### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#1]
hi, i tried to compile the RNArtist following the instruction, but I came across this error,

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 19 source files to /home/parallels/biosoft/RNArtist/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.677 s
[INFO] Finished at: 2021-01-01T12:02:14Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (java-compile) on project rnartist: **_Fatal error compiling: error: release version 15 not supported -> [Help 1]_**
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

it seems I used Java 15, however, when I checked the version issue by using mvn -version, I am using java 11,

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-2.el7_9.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"

could you give me some suggestions about what may happen?

thank you very much!!

**Comment by fjossinet** [comment]
Hi. 

Sorry for this late reply. In the pom file, you can change the property java.version to fit your needs. Does it help u?

**Comment by MingleiYang** [comment]
yes, it works. thank you very much.

i change the original 15 to 11. shown below!
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <java.version>**11**</java.version> 

        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>

        <kotlin_version>1.4.10</kotlin_version>

**Comment by fjossinet** [comment]
Great. I have updated the README file. Best
