### ISSUE TITLE
Error upon opening files + Missing elements in UI

### ISSUE THREAD

**Issue by m-Mueller-m** [fjossinet/RNArtist#18]
We just istalled RNArtist on a MacOS (Apache Maven 3.9.1, OpenJDK 20.0.1 2023-04-18) and it seemed to work fine but any time we try to open one of the sample files, we get the same error message (independent of file format). It also seems the user interface is missing some elements compared to the screenshots in the documentation.
I attached a two screenshots, one of the error message and one of the UI.

![Screenshot 2023-05-15 at 15 16 09](https://github.com/fjossinet/RNArtist/assets/130242771/47fe3f74-b357-428e-b723-17c71096bbbe)
![Screenshot 2023-05-15 at 15 20 24](https://github.com/fjossinet/RNArtist/assets/130242771/f11545bc-d0e5-460e-89e1-997155382d7a)

**Comment by ViridianaAvila** [comment]
same issue here

**Comment by fjossinet** [comment]
Hi. Did you install the last version from this page: https://www.jdeploy.com/~rnartist

Could you give it a try because many things have been modified and fixed. Thanks

**Comment by m-Mueller-m** [comment]
Hi, I installed the newest version with https://www.jdeploy.com/~rnartist and it worked well. Very nice program!
As far as I could see there is no option for 3D visualization as in Assemble2 yet, is there a plan to add this?
