### ISSUE TITLE
the nucleotide position doesn't show on the plot

### ISSUE THREAD

**Issue by MingleiYang** [fjossinet/RNArtist#7]
Hi, Fjossinet,

I noticed that when the RNA structure is long, the saved svg cannot be labelled with the nucleotide. The numbers of the position are only shown when you zoom in the structure.

Could you give some suggestion?

My best,

**Comment by fjossinet** [comment]
Concerning the interactive plot in the app, if the font size is below a given cutoff value, the numbers are not displayed (too small to read them, so not necessary to compute them). Concerning the SVG output, this ability is not yet implemented.

**Comment by MingleiYang** [comment]
Hi,fossinet,

Thank you for your reply.

if we would like to generate the publishable figure, the labels of the number is very important.

I think for the short RNA, it will not be a issue since the numbers always show up. However, if the RNA is long, without numbers of position labelled will be an issue.

**Comment by fjossinet** [comment]
Hi,

Numbering is now exported in SVG. You can have a look at the SVG i have just published in this gist https://gist.github.com/fjossinet/40ae79445268e69cc4adbd94fb8f4af0

If you get the last RNArtist, the script editor allows you to add the svg or png elements for export. Using the height/width attributes, you can increase the size of your picture to display the numbering if needed.

Let me know
